version: '3'
services:
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 8001:8001
    networks:
      - app_network
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=8001
networks:
  app_network:
    external: true