version: '3'
services:
  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    ports:
      - "4040:4040"
    networks:
      - app_network
    command: ngrok http 3002
  backend:
    container_name: backend
    platform: linux/amd64
    depends_on:
      - ngrok
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 3002:3001
    networks:
      - app_network
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NGROK_URL=ngrok
networks:
  app_network:
    external: true